project:
  name: "WPMoo"
  namespace: "WPMoo"
  text_domain: "wpmoo"

localization:
  team: "WPMoo Team <hello@wpmoo.org>"
  translator: "WPMoo <hello@wpmoo.org>"
  bug_reports: "https://github.com/wpmoo-org/wpmoo/issues"
  copyright_text: |
    # Copyright (C) 2025 WPMoo.org
    # This file is distributed under the GPL-2.0+.

dev:
  browser_sync:
    enabled: true
    url: "https://wp-dev.local"
    port: 3000
    open: true
    notify: false
    files:
      - "./**/*.php"
      - "./assets/js/**/*.js"
      - "./assets/css/**/*.css"
  theme: "azure"
